export const ES_TYPES = {
    electric:  'Eléctrico',
    normal:    'Normal',
    fire:      'Fuego',
    water:     'Agua',
    ice:       'Hielo',
    rock:      'Roca',
    flying:    'Volador',
    grass:     'Césped',
    psychic:   'Psíquico',
    ghots:     'Fantasma',
    bug:       'Bicho',
    poison:    'Veneno',
    ground:    'Tierra',
    dragon:    'Dragon',
    steel:     'Acero',
    fighting:  'Lucha',
    default:   'Default',
}

export const EN_TYPES = {
    electric:  'Electric',
    normal:    'Normal',
    fire:      'Fire',
    water:     'Water',
    ice:       'Ice',
    rock:      'Rock',
    flying:    'Flying',
    grass:     'Grass',
    psychic:   'Psychic',
    ghots:     'Ghots',
    bug:       'Bug',
    poison:    'Poison',
    ground:    'Ground',
    dragon:    'Dragon',
    steel:     'Steel',
    fighting:  'Fighting',
    default:   'Default',
}